service: api-examples

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  httpApi:
    authorizers:
      authorizer:
        type: request
        enableSimpleResponses: true
        functionName: authorizer

package:
  individually: true

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    packager: "yarn"
    includeModules: true

functions:
  authorizer:
    handler: src/authorizer/index.handler
  echo:
    handler: src/echo/index.handler
    # ssm infra parameters example, no actual reason to run inside vpc
    vpc:
      securityGroupIds:
        - !Ref SecurityGroup
      subnetIds:
        - ${ssm:/examples/infra/vpc/private-subnet-0/id}
    events:
      - httpApi:
          method: get
          path: /echo
          authorizer:
            name: authorizer

resources:
  Resources:
    SecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: example-lambda
        GroupDescription: example-lambda
        VpcId: ${ssm:/examples/infra/vpc/id}
